import type { User, Patient, Specialty, Doctor, Appointment, DoctorException } from './types'

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'admin@clinica.com',
    password: 'admin123',
    role: 'admin',
    name: 'Carlos Administrador',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user-2',
    email: 'doctor@clinica.com',
    password: 'doctor123',
    role: 'doctor',
    name: 'Dr. Juan Perez',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user-3',
    email: 'recepcion@clinica.com',
    password: 'recepcion123',
    role: 'receptionist',
    name: 'Maria Recepcionista',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user-4',
    email: 'paciente@email.com',
    password: 'paciente123',
    role: 'patient',
    name: 'Pedro Paciente',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user-5',
    email: 'doctora@clinica.com',
    password: 'doctora123',
    role: 'doctor',
    name: 'Dra. Ana Garcia',
    createdAt: new Date('2024-01-01'),
  },
]

export const mockSpecialties: Specialty[] = [
  { id: 'spec-1', name: 'Medicina General', description: 'Consulta medica general y preventiva', active: true },
  { id: 'spec-2', name: 'Pediatria', description: 'Atencion medica para ninos y adolescentes', active: true },
  { id: 'spec-3', name: 'Cardiologia', description: 'Especialidad del corazon y sistema circulatorio', active: true },
  { id: 'spec-4', name: 'Dermatologia', description: 'Especialidad de la piel', active: true },
  { id: 'spec-5', name: 'Ginecologia', description: 'Salud de la mujer', active: true },
]

export const mockDoctors: Doctor[] = [
  {
    id: 'doc-1',
    userId: 'user-2',
    name: 'Dr. Juan Perez',
    specialtyId: 'spec-1',
    consultationDuration: 30,
    workDays: [1, 2, 3, 4, 5],
    startTime: '08:00',
    endTime: '16:00',
    consultRoom: 'Consultorio 101',
    active: true,
  },
  {
    id: 'doc-2',
    userId: 'user-5',
    name: 'Dra. Ana Garcia',
    specialtyId: 'spec-2',
    consultationDuration: 20,
    workDays: [1, 2, 3, 4, 5, 6],
    startTime: '09:00',
    endTime: '17:00',
    consultRoom: 'Consultorio 102',
    active: true,
  },
  {
    id: 'doc-3',
    userId: 'user-6',
    name: 'Dr. Roberto Sanchez',
    specialtyId: 'spec-3',
    consultationDuration: 45,
    workDays: [1, 3, 5],
    startTime: '10:00',
    endTime: '18:00',
    consultRoom: 'Consultorio 103',
    active: true,
  },
]

export const mockPatients: Patient[] = [
  {
    id: 'pat-1',
    userId: 'user-4',
    fullName: 'Pedro Paciente',
    cedula: '1234567890',
    birthDate: '1985-05-15',
    phone: '0991234567',
    email: 'paciente@email.com',
    active: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'pat-2',
    userId: '',
    fullName: 'Maria Lopez',
    cedula: '0987654321',
    birthDate: '1990-08-22',
    phone: '0987654321',
    email: 'maria.lopez@email.com',
    active: true,
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'pat-3',
    userId: '',
    fullName: 'Carlos Mendez',
    cedula: '1122334455',
    birthDate: '1978-12-03',
    phone: '0976543210',
    email: 'carlos.mendez@email.com',
    active: true,
    createdAt: new Date('2024-03-05'),
  },
]

const today = new Date()
const todayStr = today.toISOString().split('T')[0]

export const mockAppointments: Appointment[] = [
  {
    id: 'apt-1',
    ticketNumber: 'A001',
    patientId: 'pat-1',
    doctorId: 'doc-1',
    specialtyId: 'spec-1',
    date: todayStr,
    time: '08:00',
    status: 'completed',
    requestedAt: new Date(today.getTime() - 86400000),
    attendedAt: new Date(),
  },
  {
    id: 'apt-2',
    ticketNumber: 'A002',
    patientId: 'pat-2',
    doctorId: 'doc-1',
    specialtyId: 'spec-1',
    date: todayStr,
    time: '08:30',
    status: 'in_consultation',
    requestedAt: new Date(today.getTime() - 86400000),
  },
  {
    id: 'apt-3',
    ticketNumber: 'A003',
    patientId: 'pat-3',
    doctorId: 'doc-1',
    specialtyId: 'spec-1',
    date: todayStr,
    time: '09:00',
    status: 'waiting',
    requestedAt: new Date(today.getTime() - 43200000),
  },
  {
    id: 'apt-4',
    ticketNumber: 'A004',
    patientId: 'pat-1',
    doctorId: 'doc-2',
    specialtyId: 'spec-2',
    date: todayStr,
    time: '09:30',
    status: 'waiting',
    requestedAt: new Date(today.getTime() - 43200000),
  },
  {
    id: 'apt-5',
    ticketNumber: 'A005',
    patientId: 'pat-2',
    doctorId: 'doc-1',
    specialtyId: 'spec-1',
    date: todayStr,
    time: '09:30',
    status: 'waiting',
    requestedAt: new Date(today.getTime() - 21600000),
  },
  {
    id: 'apt-6',
    ticketNumber: 'A006',
    patientId: 'pat-3',
    doctorId: 'doc-1',
    specialtyId: 'spec-1',
    date: todayStr,
    time: '10:00',
    status: 'scheduled',
    requestedAt: new Date(today.getTime() - 21600000),
  },
  {
    id: 'apt-7',
    ticketNumber: 'A007',
    patientId: 'pat-1',
    doctorId: 'doc-1',
    specialtyId: 'spec-1',
    date: todayStr,
    time: '10:30',
    status: 'scheduled',
    requestedAt: new Date(today.getTime() - 10800000),
  },
]

export const mockExceptions: DoctorException[] = [
  {
    id: 'exc-1',
    doctorId: 'doc-1',
    date: '2026-04-25',
    reason: 'Vacaciones',
  },
]
